PATHS:

  # Path to assets folder
  assets: "./dev/"

  # Path to dist folder
  dist: "./dist/"

  # Paths to fonts
  fonts:
    - "dev/fonts/*"
    - "bower_components/bootstrap-sass/assets/fonts/bootstrap/"

  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "bower_components/bootstrap-sass/assets/stylesheets/"

  # Paths to JavaScript libraries, which are combined into one file
  javascript:
    # Libraries
    - "bower_components/jquery/dist/jquery.js"

    # Bootstrap files
    - "bower_components/bootstrap-sass/assets/javascripts/"
    - "bower_components/jquery-smooth-scroll/"

#    - "bower_components/bootstrap-sass/assets/javascripts/bootstrap/affix.js"
#    - "bower_components/bootstrap-sass/assets/javascripts/bootstrap/alert.js"
#    - "bower_components/bootstrap-sass/assets/javascripts/bootstrap/button.js"
#    - "bower_components/bootstrap-sass/assets/javascripts/bootstrap/carousel.js"
#    - "bower_components/bootstrap-sass/assets/javascripts/bootstrap/collapse.js"
#    - "bower_components/bootstrap-sass/assets/javascripts/bootstrap/dropdown.js"
#    - "bower_components/bootstrap-sass/assets/javascripts/bootstrap/modal.js"
#    - "bower_components/bootstrap-sass/assets/javascripts/bootstrap/popover.js"
#    - "bower_components/bootstrap-sass/assets/javascripts/bootstrap/scrollspy.js"
#    - "bower_components/bootstrap-sass/assets/javascripts/bootstrap/tab.js"
#    - "bower_components/bootstrap-sass/assets/javascripts/bootstrap/tooltip.js"
#    - "bower_components/bootstrap-sass/assets/javascripts/bootstrap/transition.js"

